#################################
# PID parameters for pose seeking
#################################

# Maximum value of error integral for all PID controllers
windup_limit: 0.05

# PID gains
x_proportional_gain: 2.0 # 1.5 # 0.025 # 0.05 # -0.00053
y_proportional_gain: 2.0 # 1.5 # -0.00125 # -0.00125 # -0.05250212502555
z_proportional_gain: 2.0 # 1.5 # -0.072 # -0.062 # -0.0616551
x_integral_gain: 0.021
y_integral_gain: 0.021
z_integral_gain: 0.021
x_derivative_gain: 0.0
y_derivative_gain: 0.0
z_derivative_gain: 0.0

angular_proportional_gain: 0.5 #0.5 #  0.002 # 0.004 # 0.0090
angular_integral_gain: 0.0
angular_derivative_gain: 0.0