controller_list:
  - name: fake_wall_arm_controller
    type: $(arg execution_type)
    joints:
      - wall_arm_shoulder_pan_joint
      - wall_arm_shoulder_lift_joint
      - wall_arm_elbow_joint
      - wall_arm_wrist_1_joint
      - wall_arm_wrist_2_joint
      - wall_arm_wrist_3_joint
  - name: fake_ceiling_arm_controller
    type: $(arg execution_type)
    joints:
      - ceiling_arm_shoulder_pan_joint
      - ceiling_arm_shoulder_lift_joint
      - ceiling_arm_elbow_joint
      - ceiling_arm_wrist_1_joint
      - ceiling_arm_wrist_2_joint
      - ceiling_arm_wrist_3_joint
  - name: fake_dual_arm_controller
    type: $(arg execution_type)
    joints:
      - ceiling_arm_shoulder_pan_joint
      - ceiling_arm_shoulder_lift_joint
      - ceiling_arm_elbow_joint
      - ceiling_arm_wrist_1_joint
      - ceiling_arm_wrist_2_joint
      - ceiling_arm_wrist_3_joint
      - wall_arm_shoulder_pan_joint
      - wall_arm_shoulder_lift_joint
      - wall_arm_elbow_joint
      - wall_arm_wrist_1_joint
      - wall_arm_wrist_2_joint
      - wall_arm_wrist_3_joint
initial:  # Define initial robot poses.
  - group: wall_arm
    pose: home_wall
  - group: ceiling_arm
    pose: home_ceiling