# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  ceiling_arm_elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  ceiling_arm_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 2.09439510239
    has_acceleration_limits: false
    max_acceleration: 0
  ceiling_arm_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 2.09439510239
    has_acceleration_limits: false
    max_acceleration: 0
  ceiling_arm_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  ceiling_arm_wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  ceiling_arm_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  wall_arm_elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  wall_arm_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 2.09439510239
    has_acceleration_limits: false
    max_acceleration: 0
  wall_arm_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 2.09439510239
    has_acceleration_limits: false
    max_acceleration: 0
  wall_arm_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  wall_arm_wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  wall_arm_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  wall_track_slider_joint:
    has_position_limits: true
    min_position: 0
    max_position: 3.19
  ceiling_track_slider_joint:
    has_position_limits: true
    min_position: 0
    max_position: 3.19